name: Create PR for update all submodules

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: git config
        run: |
          git config --global user.name "bot[github]"
          git config --global user.email "bot@github.com"
      - name: Update all submodules and create PR
        env:
          NEW_BRANCH_NAME: update_submodule
          NEW_COMMIT_TITLE: "feat: update submodule"
          NEW_COMMIT_BODY: "Create by action"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git submodule update --remote
          DIFF_TEXT=$(git diff main)
          DIFF_COUNT=$(echo -n $DIFF_TEXT | wc -l)
          RETURN_CODE=0

          if [ $DIFF_COUNT -gt 0 ]
          then
            echo "update found"
            echo $DIFF_TEXT
            
            git checkout -b $NEW_BRANCH_NAME
            git add .
            git commit -m "$NEW_COMMIT_TITLE"
            git push -f origin $NEW_BRANCH_NAME

            gh pr create --base main --title "$NEW_COMMIT_TITLE" --body "$NEW_COMMIT_BODY"
          else
            RETURN_CODE=1
            echo "no updates"
          fi
          exit $RETURN_CODE