name: Create PR for update one submodule

on:
  workflow_dispatch:
    inputs:
      submodule:
        description: 'module to update'
        required: true
        # default: 'warning'
        type: choice
        options:
          - acme/modules/a
          - acme/modules/b

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ github.token }}
      
      - name: git config
        run: |
          git config --global user.name "bot[github]"
          git config --global user.email "bot@github.com"
      - name: Update submodule and create PR
        env:
          NEW_BRANCH_NAME: update_single_submodule_${{ github.sha }}
          NEW_COMMIT_TITLE: "feat: update submodule ${{ inputs.submodule }} ${{ github.sha }}"
          NEW_COMMIT_BODY: "Create by action"
          GH_TOKEN: ${{ github.token }}
        run: |
          git submodule update --remote ${{ inputs.submodule }}
          DIFF_TEXT=$(git diff main)
          echo $DIFF_TEXT
          DIFF_COUNT=$(echo -n $DIFF_TEXT | wc -l)

          if [ $DIFF_COUNT -gt 0 ]
          then
            echo "update found"
            
            git checkout -b $NEW_BRANCH_NAME
            git add .
            git commit -m "$NEW_COMMIT_TITLE"
            git push -f origin $NEW_BRANCH_NAME

            gh pr create --base main --title "$NEW_COMMIT_TITLE" --body "$NEW_COMMIT_BODY"
          else
            RETURN_CODE=1
            echo "no updates"
          fi
          exit $RETURN_CODE