name: Create update PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository with submodules
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # Checkout all submodules recursively
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for private submodules
      
      - name: git config
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
      - name: Update and create pr
        env:
          NEW_BRANCH_NAME: update_submodule
          NEW_COMMIT_TITLE: "feat: update submodule"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git submodule update --remote

          DIFF_COUNT=$(git diff main | wc -l)

          if [ $DIFF_COUNT -gt 0 ]
          then
            echo "update found"
            git checkout -b $NEW_BRANCH_NAME
            git add .
            git commit -m "$NEW_COMMIT_TITLE"
            git push -f origin $NEW_BRANCH_NAME
            gh pr create --base main --title "$NEW_COMMIT_TITLE"
          else
            echo "no updates"
          fi